# tmux list-keys to view active keybindings
# <prefix> ? to list keybindings

# ====== TERMINAL ======
# tmux-256color had compatibility issues over ssh. Fixed with an alias
set -g default-terminal "tmux-256color" # screen-256color / tmux-256color 
set -g terminal-overrides "linux*:AX@"
set -ag terminal-overrides ",*:RGB" 
set -ag terminal-overrides ",alacritty:Tc"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g xterm-keys on

# ====== GENERAL ======
# keep plugin and theme installations outside the .config directory
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'

# change the prefix from 'C-b' to 'C-space'
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# mouse control
set -g mouse on

# kill session on ctrl+D
unbind C-d
bind-key C-d kill-session

# ====== KEY BINDINGS ======
# start window and pane indexing from 1
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# vi copy mode <prefix>+[ -- copy with space 
setw -g mode-keys vi

# split panes (with ssh-split)
unbind '"'
unbind %
set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-h-key "\\"
set-option -g @ssh-split-v-key "-"

# pane navigation
bind-key -n C-h select-pane -L
bind-key -n C-l select-pane -R
bind-key -n C-k select-pane -U
bind-key -n C-j select-pane -D

# resize panes
bind-key -n M-h resize-pane -L 5
bind-key -n M-j resize-pane -D 5
bind-key -n M-k resize-pane -U 5
bind-key -n M-l resize-pane -R 5

# copy mode
bind-key -T copy-mode-vi p send-keys -X search-backward "❯"
bind-key -T copy-mode-vi o send-keys -X search-backward "\\\$ "

bind-key N display-popup -E 'NVIM_APPNAME="avim" nvim ~/notes/quick-note.md'

# ====== STATUSLINE ======
# Set background and foreground to 'default' to inherit Alacritty's colors
set -g status-style bg=default,fg=default

# Left side: Session name (lualine_a style)
set -g status-left-length 40
set -g status-left "#[bg=green,fg=black,bold] #S #[bg=default] "

# Window list (lualine_b/c style)
set -g window-status-format "#[bg=black,fg=white] #I #W "
set -g window-status-current-format "#[bg=colour8,fg=white,bold] #I #W "
set -g window-status-separator ""

# Right side: Pane Title, Date, Time (lualine_x, y, z style)
set -g status-right-length 150
set -g status-right "#[bg=black,fg=white] #{=21:pane_title} #[bg=colour8,fg=white] %d-%b-%y #[bg=green,fg=black,bold] %H:%M "


# ====== IMPORTS ======
# example fzf menu entries
TMUX_FZF_MENU=\
"foo\necho 'Hello!'\n"\
"bar\nls ~\n"\
"la\nls -la\n"

# plugins (install with <prefix>+I)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # a bunch of settings that should be default 
set -g @plugin 'sainnhe/tmux-fzf' # <prefix>+F - manage sessions, search commands and keybindings
set -g @plugin 'pschmitt/tmux-ssh-split' # new panes automatically ssh if needed
set -g @plugin 'noscript/tmux-mighty-scroll' # smooth mouse scrolling
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name' # fancy window names, needs yq
set -g @plugin 'schasse/tmux-jump' # <prefix>+j to jump to char (might delete)

# themes
# set -g @plugin "nordtheme/tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.local/share/tmux/plugins/tpm/tpm'

# personal notes
# C-o in TmuxAI allows you to edit the prompt with a text editor
# TmuxAI has many neat features: https://github.com/alvinunreal/tmuxai?tab=readme-ov-file
# It also privdes a nice page showcasing tmux keybindings: https://tmuxai.dev/tmux-cheat-sheet/
